title: Brian's Projects Portfolio
logo: cyber-security-logo-design-vector-27946829.jpg
description: Minimal is a theme for GitHub Pages.
show_downloads: false
google_analytics: 
theme: jekyll-theme-minimal
github:
  zip_url: www.linkedin.com/in/brian-smith-853a17223
  another_url: another value
